apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: ocp47-2021-2
  host: github.com
  org: hc-gitops-test2
  owner: hc-gitops-test2
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/hc-gitops-test2/multi-tenancy-gitops-apps.git
