apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgCu7bAapYVeqxnsvNlyBwy8Ok5Kmroe2hSKyzKhh/4c8c/P7Mh9vpc7LzJYl9j/W1bpswMPrvTPdVJ9dGlWcMrKz75DsLwq7qUVByBnHikIPjylsYd2oDHdmkxctiIFH17BqoEb1A/w6RLPXFMaOua1xJGzjreTQbwKkdm5tACmpLbSFBzYrWnxeRFPMxXpq/G8zTGTAhWIJGLTSepFxFqELkHQVy4KS99k/0YXAPU+rk6uJoH8yOxYGOUFogBbhTM2PkyXeo6vgbXlw5p6OYWCdImSI4p0CRELO8LEb9jzvwUV/K6D32htuy1zfoHg5tSTGTN8k/5yC+5cFsMOOCIu/QoutaIXLvfdICp1B/KpUMhbarNnx5swlnA582pKQJjhJ0dCLiJp0HxH4XunL314creT3PpyBuHWbZPt0M0e/MCaxrLfxbFIG00TEGRs9CQNr0tNIygn0SttFyljE4wZVTF06q8dNerGjtAmu4lX7vd0SN61X2RbvtDxle5dKw91OrixRfVnqFRsI/RGi9Vp1K8xZw5awbeqOJdDerBRs87HldPoHWR2pXPc0Yc3H2DqlsE4mc45gkYf0Pc9TADrTfYCgKJL2xneR6HBa/ECAAow497JuGg2xCGQwq8+t20KdaxnEFBkhvcRPogAPaqndRt3Wa5r9TzCWMDBa3M5d4CDBffVwopP0Il20/YmcUfXB63hlNvXlWN9HS9ByWJf030xPD55vRZUVdjWNEI7Ii9L4Tb13w==
    ARTIFACTORY_PASSWORD: AgCi/l5dgtK5eDyfnFFWTHzxLjNqhBti/zbkUsT1TV9ZwE5q46I5kO4saaZboQNWMqGmA0lUtaXQIL4C1rkclKDgtgqECerpXfm966pG9qw2D60senIhxIH/Clx51Da4shUPzF46I0PFfU4XjFF9Wo27zhcv32NeBJfg7XTEQgDxahjPPNSCJl+h1s/qOEP59PZ87PQst1TS3AAsMaIcaxUT2DAOUHG2GSVuTEzSTEv7Q4Q957TmIXjnZyyeuLdRU/DsEj3tZx2Usyo/G/Z7ArciplRfpv3/8i3bei/9jmg3L3wUAtWXiFoAan1FTJytVMRoVDCIPbgD6X3N7eTyg0OeOWRT3sFMVdeJLH/0bg2tZItxnR2kIn4isIKJbAZ/q1S18Yps6jES7joX3Zbh3CKdJVqh0jKO6QPYHNA+jU4PGOJjX7284Oo7qrUKc/UGVnfgUeS9So3wgobpCgGO2t1bIzVUk8Ga4OFOvUUUkMNH2K8t24prVnIrLH7AnYzgGoPTrGVVWWUi0/lz397CK87hvUeMvklNQ9DWSQEI1IfgSL8QEzYA3OXiK2cBWw0HKvNO0LBg2gX1RKsTu9VJPT6vjdnc4zym1YBOZVF0d8K4R5FfN4VTZRitJDmqEBF9pmLmyn/RSJWTaRnU9P8b/HhbZKjHrGazz5ZKiiT3JaI2uTRvcQwd84tyrx2Fh9629wVdp/ZpoAYDpNNVNDOln9sOOf1IEQ==
    ARTIFACTORY_URL: AgAZU5JP4qcy5xjOa08vlp/p/WmZsStRKPqod1zlBKvyLSp/o4XwRrY6C/SbTNWLdj9sKPjjY/4N2ndxisnl7jMywtjPEZBbCobFC4zeabua7NYDKQWKqKfSpipTjh7iPsKr1rH1hInJVmct/5v5h1pr6eUVNkvqHngZpvq9f7v1ULMn5QabaK6QIyya1H1Yce7/PvgVDMdJgGvIGciRvR1EeQqanIzy7JQgMhmSeih2A8a4EtIBUoeBUp9sUOOZcUfcIWa4XwFmqZkSWpQkjIJEfUP+SVgNm+WDNr9fOuNZ+d6nv0GoZ06RDt9MGHDv0oQF+Bx5qYTdbPKnyiFObixYrAN+wBSgNTCGNv3yvFXnTqHoHTXTKxKoHg/4OHsVINqVpoa2jEAy5+RilHod5FKL3qX9jrZqr/zvCSKQ0wFp+7aJ4toAngzUZ6o2Z+lMPyRuOky2YYvZ9nN5F1KCNeJ3jtze+ze6DU83glR3UDIn663+oNsjGde10VzkyMd0DwfffGxc/D/mPEGNhn+1zY7x4lG7iS7FgTC8E5MhzGrDm5Z1u9FFHSk8qhmrQH1veZw6T4dXWDFcVMcnNxceVs1fViqYoqyLrLDGofwDOxdkPNiVoAAAZkXM1AFDZSpg+8dVndgzQBZ0d0s5nm2ga7/lAc6TZZhp+oV5JNva7v53B7ehX+nIZ89r/fEyoRdP98r5PkNFCwCvVsVFZ+xrgaiJJTJ1VXz+BoGSVnFhparY99jisdcUscxXKA==
    ARTIFACTORY_USER: AgBYGM3fXN6ZF2rVZSlZTWmxz1cemMFFCTIu0RkXMB0Qk52oJIPC9Z0tXKKUMQgmsqhLJ349PZexPYZINTWL7oM+2AUh5kyvefNWsUzhgiLYgtXnKUUtwkaHAg2CjmmHizk29tSEovCc6soE3o2DQYeI6oXY5HeAB+lZj/kqgxK2dLWpldZzXQljeYfteaIxY0oZ12IhFHQXfoZlOAZhylYfnqPOA8P/h4EjOI6pMntIUR1/oH8RWfoBpQJB3YsEAt0WtGx+B4jZT+oW+rr8aU9ezJmSD2+ed81z2zPshpPqvf69F0bWj3v5nRNpq1RrU9A/ZWP1Zjdj1VMLIzJe5ASWAmUk139mXBat+sFibNyKqcLZbhpxhOTiULSjwVJCC/F7EGluekGssDMBg5xoZ9fIKkat/DMiHv/q5qu6GeTsECIm5z7KpVpUI0G/CumRWk12w+78HjSLfj1N2wC/4JcFahzcD2e+2C+v+tsKmHifF4wSeoBktHaxenNbqmRkGGra74qlcEErJFiYKneNezwGBNjkdcL1qx/jtoRNEROYNTbXFG6RJutCFVskbCmJIIqB5zxZ/5Ou8SK+amK6NC1bEY8SGBo5HSxnHMQ8uxjKNowkPou3zwClMAt4LdZ0xuip0j3DU/Ol/ey2U12RMxBMZeg/4pDKsRHS0dxRbPtjmJ0aTT7uFHfvNz0fDI3z9UWaVDPUiw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:metadata:
            f:annotations:
              .: {}
              f:sealedsecrets.bitnami.com/cluster-wide: {}
            f:ownerReferences:
              .: {}
              k:{"uid":"eef2cd0d-b878-4129-8cd9-383e19a3fab0"}:
                .: {}
                f:apiVersion: {}
                f:controller: {}
                f:kind: {}
                f:name: {}
                f:uid: {}
          f:type: {}
        manager: controller
        operation: Update
        time: "2021-08-20T20:06:09Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

