apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgAr3jNG2Lat5Ry0C1l8784jAX2bFk4pLuhKYOBB8jzeRaWT/Lmd0mY3V71EjEw771zlqTuThfvwsSMnFtn0vwt0BAl3Gi0k+QOUG2a5kujRLZjY/1ZGcmZ1dD+CuRoleRpzAUNo3Ry7yWopWRuZSt3sYGufRDRLcGbaRhqhlcwRrnswn1S7HTh6HRN9+0AuN+vNMlATYFm018LMrnOhYgQR/zftho7x0Cgl5/DMupGl2DoZXvslZcsjo9NONCX+Ow825lbUbSQJE2uYlkK43uUz0D9tNkUuy1SH78PQOZofcLULUFjIpdWh5RrwHtVXWwWLmbf/EjudssNtMIVDOh4Ql1iojkaGZy+aIoOGmDeNqzTBP+5cUVQ9fCu+aER0FGrVbbyk/3MCTq3FfDW1pf1l90DPuEx4JIIt1z2wmGoyH5nPVlZawbyE5cxQZxWPikQdKw8b97kxBB1BENfVaObeZAQw1dc2gwRNngsbuTSR3KjWOR/zXE4/C+iy7qR1z3GUm/IwnOb18napfzOfPKLC6YLkW60dJ6iCOewl8rr31RGNRdrmp34Go/G/ukEYLavwTaO2CIaRvPVmKoe9WBfHvUBKYJlLfVMq1W++30ua/+iMyuH+4QDwTHa/+b+Ad90eEXVfspoEe3I8ZrBpZYJKS2dgUl92DVIkbn4Rf4DvCfFo5Kph9IvQo6EOeUdVVXDF4yJ8MYjFWjms3uv+p/hELV5JypUCSsh/5uxctPjd2ceYSnf51g==
    ARTIFACTORY_PASSWORD: AgAjajRaK4usdrW+DhWMlEpEsXrOKoGljz0ty7yOw3yoWVDURUH4f2J04GwytT4/rVDWCcYIVpMR10ZKs7wydaxC19eFTBKPWf6tz+Q9J0Xx3hTuSDwpa13gFB3SM9WJKEL0GcjXWUtiWm6w3oSNfpMNEr+DO8WJFRp8d9bPZH18k8MAoAnI7WeaPZyi0Wpu1WchwYcDXgFQ49QNo6s/irfZa2k8MmXDHnDZoXiLodCS0Er3LRCROLqUqBwstfDH1mDLG4cYAAm3p+dy30y77TWcEu8h8WakCWuFeFFfvHxRA+lYUUoJj8FseH4kA1XIJ4GKpvOqmZTIwDAXEm+WM5aCFe47WOo1LwgUAWbIAgOJ+/oEibcyZ3V/Z35lUUqi+hrVwQckAP3ufzSvm5fXtMwUofO1u9PpRwMB6seOrFMYdtx8sxLwCr7ziJCO3ZaWajAKmrvIdSn41wlFRWxI/iPz+DA5BQEXqCaG8V0twfCTSo0T6l3fF+upV+p9QdETr/QJ9b3VCh4FnZzU4cYH2u5OdpzfFNzPUqrY40NOsaM8aqSmctaPzSUuTnRSCQa49PC68BaFtd8TkA+OkumkGFUOTdHLBDgM7pqHGksXxPogobICTLG0iJfFakvQoxPCO2dvuw2M0BL1FdMM+f980tJ35tiGsC+Qv+GowZCyAi7lEXXr6b9L4WbVD4bA5FmhtsGWPcHgEYovt+mqAFC68XzKDmKTNg==
    ARTIFACTORY_URL: AgAtQ2FaoRzRevCLMz4JRJ61Z86D7GYXSFCnBNM23xUmw5KDOdXo1Q0LM5CrpOvnzytth79QJMRKkivg42FwMrNzdzxSpsGWhdSVsDa0/lqfLjgcUnqMD/DCgm6/Dx4VM3W+9n85mXR5BZaSlpa4z+cyL+nQ98AihoAhck8WXuFJxngnj6kuhyxOqYiofl7Ofo97/AoAVFqWbtVRPBkoe1QqFY9g1p9EcEI4PdbNo4O4yFEciXXPtqV4/WWeTxzPX8r/7PWgEUxFjVtSHxhBcEmHDLNXa0/JDxntc48C75x5eAQvfTXU0xIGgnhGKxE8sz/elw7CEFIKdi9IXT0JjQFN3vhcpoAGH+FkE/ITUirj6Fv0VJcvJ0vrlj92KPcvBdiPUMgsWedl8FETcdIcaerMY2m3ZJYv9hxn6xOh8lG5y9ZAXa5nNtTIXSr6onR5mWwTncabBYvOA4THW+ZOGoSJZdh1jZY2M5qc3oOQYeNMye4W2/5MLxXv7/Szf6ke3D08zDzNSLoQGTUiKxzaIY3wpkCSo8krwjp0+Gnj4NLnmccJgsIT+pcFjWqiLvjc/NaHGFvpm46qCOyMBgV2d9zAN3xb/IACOFHT3FTb9kIKDftxja/rTXtFtot60hCr0WdRoNmFbZWkRAdQLliIXVvaWkX/J+CYMNnhmgiGQJheFwaezxpw0Z9X7iKPMeqdzz98Z1c2Kq3kopUvP+IZxagW7wcFqwlYa42/tBJZVW9DdkLBn9ETVnH22A==
    ARTIFACTORY_USER: AgAa9fas3tehXIM1ReZOXETW83A8nQAEKhzCCbNxdvJ80hEc++op+7ggJ95lUhmW57E/+H9nnMv6qxxjlGaBVFCEJCyEXy9OtQQW3ptXmELRJLxGLxNSEfJQd4OEWPmfKOhMDczXLLqBdqPxsduVcSrlK0nEZx499FAg3em9S3zEhuveMbx5vrM75GVKz0fdmLaECIkwUdUaOSOO/7dxGV8uGtEgXaw4RS4rh9N7he51pkNNNaWXrSwuas97o1Yxh5bIj1NsErcMUhCjOq7nH1Izh+YQXse7TL0bf/tf7LK3nBuk9nu8vaIyofxOtNWuErwbEfdC0LrRtjwJvahA1SQAvV1Sw0sM0K6UFc2VVl7qJCEy8ngKr7YuzOFN4jTG5AJ6s+R5OZT7LO4qoC4HZU8Lz9YOEHeExp8O74/kYdMifBn8V+cQNViEIJqxm/tTmH1VpnQznPfTCN9TWZ2hxL2vSNGkHNQ/PdZrpNn/ksBZWJSZFAmgvZ6v9m5FZLVfblxJmz/qb8Q8vBvRqYQnJM2FcoNGBINNKM7Beiq1YloOUvkilKBp3ybS5creNO52vEPOCjAqEmEWAlAjWRo9MbmVkfpsMBVrDopbv3twqpo5fbEbOb7T6HqyVk1VHYq4Ed30pub7grLncBSWIYV3B/eq9OposDX8FsNT5TXciaOXZOTRRFCOzdGZs3EwTHjYZDRiVzD8Bg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2021-08-20T07:12:37Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2021-08-20T07:13:51Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

