apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgAMw4MDvcPEnKsC75+ctyUm1XEeBkDL9CbvNPIQcC3w5JvZEume4LSltgJdJrn7GLTyrr4p//dVHpDzwoh4pw6tebeQzEeGOY8Y+BFEntuF3i6pmI8mCg6NT7qlPN4UKZK/HLDSjTbB3uYz8S/zIjmoJsa5ZJX7Ngf2F/ylu4qRLcjVZDUki7dmX4vHYz4KFVgQl4ELMgtjvvU1orBilWaL6YGYMlqZWQKcHd76r09U+4pd4n5Aakc+zCaZgiRiSwDRS7B69nPBgAXyP6PWjRoPo+5+mmEtWCTser9Fich8CpOpIFuFFcs2PYc5BgDeDL2UQ/uf++dRrFQuyPxclebmeRTiUDAboAGaDkWSbwKcspWK9xBL426Ql3wD8Nru+Xz4VjKz7Uv2QA9to7RZ4B7rHmhD1ts3o6j8BWSOr/yhosDuN/yJbrdjbVl6a99ZTqPWjPgU37DS5txtrSiY0Of0osmRJAyF9v/oKQgi9JfbLRNnz/OsnyNyg7SDi6ADHv8R5zZOlPcsfT6c5r7u2618c7axBQSM3bQjITN+W+FZMftYRRp3aZ4U5nEChTqi2EaT52M+p30bgWNRWD01EjQ0SylMrQfp4Esnat6qFMdcTjV+hMoqzgixM8wLnEmANmCDatJZ/M52f08eA1Bglr8ZGsZwzIaE4MVZNLg+OYV6X/XwwMq311TdilwCv9qdNj/F56okkj2InsbDun4uR0fPqAVvIB6/Svcea7XjdDk4BntX0d9CAQ==
    ARTIFACTORY_PASSWORD: AgBPe5Ga9+oZHiDzgCL3LpDWIwhwLdCzyDoTj8uc5mFS4kaXiqmSN8YUF4Mt7J7d4lOJOSETmZYa9Qz0X23264XqNqimZmo1KiHKfKul6Pq7M29tX+vWaQKsWgz32droEECtX/BIAeFct9OhXWLtVZgoy7HDyZ7sA/pCNomWUWvC34KmMNsu/vkJyYeWXISccwVfdKlKsL6mznnQSszeg0b5US4M0R6+7a2Ix95P66zgitiD37XgutHjjhNgi/0MZQD1ErYmps9A9D2jacCoKQqr5UaNoVMpRtJEjs8Lf+A0iV+P59hrk2oydD6+hJKkYrUjok6bWpnN3m0MCHanWDtoPbcmzDzeCHpCxfV56ocMH0sIZFNqbvEco+Ah9hkLQxaXt5g1NOVOlCbrxYGEiBfBVNQRB/nOPa463r9VOk7Au7dXilFAgTuHTrYm0a11jHI7Efx6sx1RGisFqaHXF1sDRVoN4uka3PTu9x0KpHn5fUw5L7duADkrqQgsrdimfoOR9I1jAI8J+KRsJ1DS7S4w1R18ZUi0GTXilVOOggeOM5JUK8Ateb60Fu64MrLYE1YmAJx9rHLihJkyCewRaEr+739gsvKAkFqoU+Ld4RP/uOzBcpELLcdkGJJnz6XrAwRWEtf1WKG6vz9Emr94UAeqOA8VvkY2890hF6Yykq00sVimEz2EGbFsjnsFOc7SvZFHtMKdcaT3/Rdnnlc6XBeNbY1beg==
    ARTIFACTORY_URL: AgASqoVe2qYrIonX1crc2XP5wH5pORvEE/kFq+XZRsSps3CL+5wItK2knhi0puTR3uBXxQcLJtgbxEWCPywlNEvIG5B6pbabzrs6rY59+qUr81LXRmCgr5q1Wl069LtLtHbj2p+RUP3YuWrwUnk7aCxQFpAVKolviqIMLovc5Ns3h7+n+ZtGtVAH90xa8CsrNYensrO6gqVDwg7u4XuPrVYEbT3n67LCECyIRfQss7kb6ZjiI7S28bW19L4qTp13YKhvcvbLeOtLvsnHVJNiPF3f4FavjqTm/pIYJbjmKbeA4lhEGiXrdJWe7v9/dISBRy1rxNtwUW9Bv1zn74wHurxdwAebXVpmQg/yyI7JyRogHgRMJF52fBPEMM7BKzp4OMotRB56DM/35V7cQZ4HvYs+Cms5aKWS08SwhH4wbV5ZBjuXZ4uIYRmDVijd/AUiudfH/pUWsP+Z9R82NydhymXL6UWwJ9GbPiRU5+wrTAGAa9qjH0b6VBG06Ge6B8DqbRNTEwv1vIN6QvZg687xaWq1fIbs84TB2ODD+lQMaHOCuV4e3NRMIB5HRY53MYTZpb0hH0O8cL/bi9C3XJ+/AkBwscIi7mQfUWt/Npo/3BnSo4wLl9WC1wky3JJKZQeOlpFRxH2WDIv0tUzcd921rUI3IvZjcw3A+XGvR5st2dEQbxTDD1d4AAZzbb2Ai4WSVOhqDV5HPJJ+dzaAURFDVYnzdjMRIdLKQEbnY4nOhcXdNv1psD9ZjlzSmA==
    ARTIFACTORY_USER: AgB9BYuW6j3UPnh35IzzmoAXgOuLpPiw7chCDpdh+Zbc5JP+ibsxRnh6hFvgVKQcMrhN6+eFa05bFmY2Ef6J2UDqgcJ0jXj+8pL+0pyrCKUfr6DZnJWlvtMsOdjm8sBGqiFGMfiM4Yq/hXiske1JyNNu9E2NWfFTyL5ZYARW7sKBYWnaD2fpF42jXN48Yv/GynN3Q01sN+eG33MJIUGBaxVLWz9yY1K3Wtshgjg10JR5mfn7/1lRLaLYUpn2dJ2NXlR6sNLUy8VJoKf9GYj0a+iENztgHjPDgcMFB0h5iyQFvBgQmzeSAssryX6FWY3e+cvQtn1Ax4OetmYxdf54pzKjzt1nuEo4EAQBgXIHG2td6V5WHeBNZveWZ1kRBsruWKxjtshP2V0L27m9yKUxY/vGxved4aQH1O2VNqDE9doVijyXquTEDFrvHJX8L12wuYi5RWH+YBngqe0ZDnmVbZjtu+u/SIfWx9QApxZHLh1tFOxTy1wfJOQ4mZTEvlz7B3qdtk7luA3sz9EcB0sKTSyaz0tdgZ1FrW2bqt+Cq+2XnFhTRt2wsQEkwFOBu7TDdsbIroDq7WawPavVGLP8p+jr9ibbu/xA3tvEnI8xV95NS21ip/DoD6p9BeepyuVQmHjvvkMmhTcpNzzaebMfrlD1Ale6TnBst0j4irhAsMs+NyPY2rNgdDId78QSbV91+FufDvWYdg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:metadata:
            f:annotations:
              .: {}
              f:sealedsecrets.bitnami.com/cluster-wide: {}
            f:ownerReferences:
              .: {}
              k:{"uid":"eef2cd0d-b878-4129-8cd9-383e19a3fab0"}:
                .: {}
                f:apiVersion: {}
                f:controller: {}
                f:kind: {}
                f:name: {}
                f:uid: {}
          f:type: {}
        manager: controller
        operation: Update
        time: "2021-08-20T20:06:09Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

