apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgClFXtnzhASMiQNMiHNWw4f2Px9SAEuk3tMeHC9AHUU48aTOjQzOBvnGGLQbQ/e/0zbjpqSeUvVqCFa2Z0wxv3XTRQkPcZ+n6E9atCAOkqngme+JihSFpsoTwbAA1LQ9ZxiDFg+OzCktz5ZTr1Hzw9TQUta7JqRaQBd7HdmosTrPuf6vwoUJSIEcruY6IynDpTh/helK72jJ3kyvR57kL86pniR5gV3xz1VxEnd90fTf2m9KmB39cQmk1W9ioC5xYRIDUpToXpazzny1Ih8zKAwrYTl+IoTYPEfuPUvPj4j1jhLqXJ6Rz+4LCjrjptFEo3jJo0ziBMrdMtORg6bocwFFm1f1fA7GelbHmmnnNbDRNC1VsIbjyJtWZlQRWGwSp9Y34jT+8QvBsRSwNUzUnKh/9aoUg2jk49Mbkv6k9nGIhxVRYKrcbvhOevwQGyM4dIPYxVejFYc33dUsz9vu/gXvgUMlPoQ2SQnzvakbLkeCbaAq9hv1b5S3ly9SiRUm6V4vo03OYTGAg3uFJLdx6+BS+qptDDq7iwXz+HjXWxlP82L2Tre/xXbuERbUx6TkiDGQ1bTfmiWqIAb+gV8ami1lGyQYmJddgIMBN8m+IPd7Dd7ofv4HmQUC2lZENhTftbpPpxiOuQsrF/VnOT17CYnrbOLgkkkHhVteuiFIzC3xC3YZwgqzlfmZD8mUVATZGgL/otTXC6HI6rwHW6i25pXilKV3dIc8VdWKthl6HudE1SW/d0dbJtB
    username: AgBt+E0souNqJS90gXCflDI4t4QQOQi6SOBmHCHhgUB2taqTQXMVAXt5jbvxUnxsxAisT2lKVDnN49iru+DLzAY+XH7KWLH1/d2CXocjDkrRrnyNesQ2F5Tm2px2eICl8V8ELtnwrVmNPLhseWkNQ+P/3adN9JXA2JK/Ey1XcMKKSonXj/in99WFBi6Uwc0NM8WCdW3Dj3b9AejoPTpAZgcixmBAzB/V38QBQ1ygtSnQ6u8Rerz/GbmHRV2AzaIDAYZOwJbg3H1QTSZEf9FFkJ3C1CaJbEni57APMHW2+AaP5xb63PgDQn3SvRqMSnCV8INBhXcJxoqAM42lci/+MJiNqoewvm/AU2GwJRuPfbgK11QlS1fke3w1qId7PKXeAl572Qh18ZPS3WvkZ/f1Y/VbtidDvMxH/Bw2YQO0YPkAGHTrYPR9amEyC8GajegI7uIaIUf676ZtVqT5LA/hxD82FLCCVimNlKnsSjYuES6VRn41aGBBJpobxqMgwxPMX8OJLGssbgVKjgY3I7YpB6cwqB6ImIhXb0lvM3f0Cc/g1rzdThr9IMdQOCgxOB0mkNTX8u47HQyxTMn3vPubVcCEfLNd6RehT/dw90Rx4FnaVmcYbihFJX1NWcGR+GKQmZaHPXcllf9OsdxARLh5lq2Xt2rzpKS9yB8PZNlNfqOB4f4IjmTC3jTIsk49t5jKWnnaotTiV9c3
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

