apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgBIVazL8zuhdmjLaT52vgJIatXvYlCRbuFQBjM1G9KLdE6EMwo4Im1kla5vrUlWlsjeb5g/p2TWRJhPg3AVuO3lcOb6Y236PzD4C6/qWm0Nkpc9Jq9u+55G4JzdNz0t8rd4rP6uhjlAUqRj4q+coADwUsz1tVASFqOHC/DH8xItz07AkMj1sEp9Eo79bH4spPgmBAZhLqwq5TMClsfBiso6p/760Aw0fR/AOLhEIWvlgtxFvohYi6DCI7xu3UXylpIbd23ywPcYSz7w0jOTV0jrQAQnjoaW4yvwjZLEfBU5oAlNKMLjJziaCefSi86MaaJ90omFgFXgC2PyZag1Ex1apGJNVxNT+1OQguSx4yhx90hjFpHW0lWYej2sgXjEAFU9y0+NT4yJRhUK9BwIITcCsZWUchrfgyIeH0Q49bbxUZroQC3j/nRhjFXRN3Rsct8VbT1QDDhdsOALzADSfyxHwVKUKA9Y3tCMQ7TD+j9w5OeSfd170mdLRPQgjbdWWqPSAf6Okr01vfNqZUEOD6pF0RIRPnodD2VTSWN+9prTxGTCNpDWWuePzKLYyeG1L1HQZlTsk5kRzLHWhelrgunUR6I6se2jBfw0UYMEgFTIQcMK53hQthytrH43f/3LybbPYy/wbYm3udj5J2aRSjceFtERYdSSz3u+AMWUJ+I9B/xl/j7cDCtr7xn/ARl8IyOK0Iya+P7rT3oaypGb+5jrDCve0/2u/RqgpUFvbmUuejHHfmiqFEnd
    username: AgBMFxtvo1gC/2BVP0lrB0u55AISVc/Qg34CgGMBd+VZc8om6jw1GZHOATfdcD1hbXEnyaj2xb7DYuAAIFxktHhLZRwQ3+eYwDf+7Q3YNhoPbU6l+J3rc9BhvKcTo6fBkVT5qRD5JsBQrfBG0ZDUCpbvIfrErwJPwGd5i2bz4M7PmgZfEKuiD0wajYFtl8qAD8smYFC7mLWEKKKJDUOGjXvBn900pXKzHrIF/SPzNf7GFvEIAPsG79BL4/yV3wSSZ+EfWOx9YddJ/rOi5RxqubjmmNissmU39a2ZlfzkfP3SND/Dw0Wt/ITtPS1hyg8tIY391TXflP35m+7GRwDT/Dmzg6smBehI03LnReOUEctYbcWtdAw31dKOqzTsWA9aEj0b3rroL2pJieOHtSCeyBNBOm+WlU06nSKJffIRxISr8Csw/FKa3aupSZGn/ibSY5pcwlV9SSXH6w56e0QNXYphCFAmLYTaluKNcZxuwqeNkq9Y2gUj/gGa224SWhDB3S2gtrBWKfzM0RUxLmp8UxKUsQAgOIsGfQHL+LdcE/h8xxFyVXaYABXsdTphkUNgpw0jl9mEtpwp0bsMWKMQz/1ENl5o32RjeXr1J+anVdeXC+1Ht88ddWYRilAyze5WWseXHSeukn5Ibx8p1dpGXFOYLWnB3M+8VTCJvyjrTlDpne6aVeeUfCSqhzfvNqDPcyPYkROp1+yF
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

