apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgCFZPPJ6yVHUtF7awnRgW7JEarYycUFrTQEFixnnqSzj0LT6xYteDnjAOZ6ehULv2xMWghGtVEqa4EHAoQH+nxaB7ZdPRD+lDN5n19pyCh3RtPhx/fqgPLbdGlelswsLRMc4j9WQiNo3bKKtP5+d4/xqq/vq0lxYDHivCrC58fDeifswMKYgaDyv4oT4FKheGW9wYNIE5XEwbIbPsOJEErWP8MOmujzxU03TfZ+q7q2NDrxtlpoBUa67hS5o+dbWEaPKfdfd0QpTccM9Bc970PZRIqHkAFBNVzH31FbsmLT/rvh44XJCJpQvLnwDytj9P8znxyUU6f246dV0QCrPlrw5WrlSblmW68EH0/l9sgvf8mJSxvd1JO6ELtBAgIHBMotRNBvIcPxEtRuw3+z6Hh+UOcxAd5w2X03dEmgWkec3eaIqPYBUFp/IXpkPKgG+Q6mr7aw5psNM/GrdJhpSHUSdbYdO5YfIovfOa9CtA3KhvMJSuOi1uWCgQUwbZN5H239xSnEc1D+hjq3PikItspZOyDDyoR/tsmJQrVGhp0KX03ArtJr0qM7zlzWLcfjK4fncnsbTnPWi9kARE3BFt3Q8fJVG/yDZCkjafAGq0Yr8IqEB8Rs1u9xt1Oz8yI3iDoYF6cUsdOpxNpxQ863F/yGbHYxIL/UfSLXIiPXsSxypQyKG8RLL+qVS8IHvJk8sOaunQU3ObnfehcZyd66vi757LvcfS+fIsbli4NpjrvhCQPy2TH/lfA6
    username: AgCjlcrIT3entGYLn+MQK8pVtcX3UH0njvwr5qxez7dpSWzBtvk86MHvRw6/jRomZNxQ+BFSQtu7+C6Z2CID6eV3XSJm2XR8i4mlyIfgAOYX4EjFb5VY4e4ckeW5yu2DG35GHdFFWM4XQ+v3d27mYhBxf8kB+Yv9c66T0mvydGjIjAf1Rq7vDnuIEjaD5asXsfx2c/WC7KKBP52M3MvOJpm2kQ2bJ7/VngqpPa7f6B0pmDJhqso/mAMUmUt3cTzVQf08On78HoWxdTie79k2BrXxVhmtjXs6opYYuERN2dzNj/jgTZkGY7E0fsxxwegq4PvjDiSEzXUmq4lhREiUor44NcsOZuCUMMq8Y37mM462KJVqYa2Nmf9o/7VfyVANP2zCIXEwmYSH8L1B6QSq9xJGzCNTx/27Pb+7Rq9bD7TCu54Rnj2yQ85aXtyWa4IbMKvi3LincgILysswtBngD5cnbjNxsQGtJwHAmSD3vNP6oA3lOWL1uc1rdIfpZBPZ8A9u0fUEmfE/AcQdEU4WKEjsChf62Ux4kI2qLrobWtkI6ZeFYPeeQXhgvgNzmSHJCdfpLopAVcITGhcfjhfqSAa8DGYWmczX01Qv4eM+csf0MGW1xxbQFwv/3s7OePNBzuakQXB4w3427CGORKgv8biT2CyiRe9cxllccyDHEQEgiZ9sm6Zltzv0rEDf5GjbN1eG+APh5eRl
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

